# This is a basic workflow to help you get started with Actions

name: CI_2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "test_var" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Print the log file
        run: echo The Log contains $(cat log.md)

      # Prepares the upload directory name by using the name of the branch but replaces all hashtags
      # to underscores because hashtags are not allowed on nexus upload paths
      - name: Prepare upload directory name
        id: directory-name
        run: echo "name=$(echo ${{ github.ref_name }} | sed 's/_/*/g')" >> $GITHUB_OUTPUT

      - name: Test upload directory name
        id: test-directory-name
        run: echo "name=$(echo _test | sed 's/_/*/g')" >> $GITHUB_OUTPUT

      - name: Test upload directory name 2
        id: test-directory-name-2
        run: echo "name=$(echo #test | sed 's/#/_/g')" >> $GITHUB_OUTPUT

      - name: Testing2_
        run: | 
          echo Testing2_...
          echo 'r' ${{ steps.test-directory-name.outputs.name }}
          echo 'r' ${{ steps.test-directory-name-2.outputs.name }}

      - name: Testing
        run: | 
          test_var=$(echo ${{ github.ref_name }} | sed 's/#/_/g' | sed 's/_/-/g')
          echo Testing...
          echo $test_var
          echo ${{ github.ref_name }}
          echo $GITHUB_REF
          echo $GITHUB_WORKFLOW
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_ATTEMPT
          echo $GITHUB_REF_NAME
          echo $GITHUB_JOB
          echo $GITHUB_HEAD_REF
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_BASE_REF
          echo $GITHUB_ACTIONS
          echo $GITHUB_ACTION
          echo "$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER"
          echo ${{ github.ref_name }} | sed 's/#/_/g' | sed 's/_/-/g'
          echo ${{ github.ref_name }} | sed 's/_/*/g' | sed 's/_/-/g'
          echo "${{ github.workflow }} #${{ github.run_number }}"
        
      - name: Testing2
        run: | 
          echo Testing2...
          echo 'r' ${{ steps.directory-name.outputs.name }}
          echo ${{ steps.directory-name.outputs.name }}
          curl -H X-Header-1:$test_2 -H X-Header-2:$test_version -H X-Header-5:$test_7 -H X-Header-6:${{ steps.directory-name.outputs.name }}

      # Runs a single command using the runners shell
      - name: Run markdown lint
        run: |
          npm config set fund false 
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      - uses: actions/upload-artifact@v3
        with:
          name: remark-lint-report
          path: remark-lint-report.json
              
