# This is a basic workflow to help you get started with Actions

name: CI_2

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "test_var" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Print the log file
        run: echo The Log contains $(cat log.md)

      - name: Update repo name
        id: replace-repo-name
        run: |
          echo "your if else logic here, if all ok, set the output to true"
          echo "rname=asd" >> $GITHUB_OUTPUT
          echo "bname='qwe'" >> $GITHUB_OUTPUT
          echo "tname=${{ github.ref_name }} | sed 's/_/*/g'" >> $GITHUB_OUTPUT
          echo "sname=(${{ github.ref_name }} | sed 's/_/*/g')" >> $GITHUB_OUTPUT
          echo "vname=$(echo ${{ github.ref_name }} | sed 's/_/*/g')" >> $GITHUB_OUTPUT

      - name: Testing
        run: | 
          test_var=$(echo ${{ github.ref_name }} | sed 's/#/_/g' | sed 's/_/-/g')
          echo Testing...
          echo $test_var
          echo ${{ github.ref_name }}
          echo $GITHUB_REF
          echo $GITHUB_WORKFLOW
          echo $GITHUB_RUN_NUMBER
          echo $GITHUB_RUN_ID
          echo $GITHUB_RUN_ATTEMPT
          echo $GITHUB_REF_NAME
          echo $GITHUB_JOB
          echo $GITHUB_HEAD_REF
          echo $GITHUB_EVENT_NAME
          echo $GITHUB_BASE_REF
          echo $GITHUB_ACTIONS
          echo $GITHUB_ACTION
          echo "$GITHUB_WORKFLOW #$GITHUB_RUN_NUMBER"
          echo "${{ github.workflow }} #${{ github.run_number }}"
        
      - name: Testing2
        run: | 
          echo Testing2...
          test_2=$(echo ${{ github.ref_name }} | sed 's/#/_/g' | sed 's/_/-/g')
          test_6=${{ github.ref_name }}
          test_7="${test_6//_/-}"
          test_version=$(echo ${{ github.ref_name }} | sed 's/#/_/g' | sed 's/_/-/g')
          echo "upload directory: $test_version"
          echo $test_8
          echo ${{ steps.replace-repo-name.outputs }}
          echo ${{ steps.replace-repo-name.outputs.bname }}
          echo 'r' ${{ steps.replace-repo-name.outputs.rname }}
          echo ${{ steps.replace-repo-name.outputs.tname }}
          echo ${{ steps.replace-repo-name.outputs.sname }}
          echo ${{ steps.replace-repo-name.outputs.vname }}
          curl -H X-Header-1:$test_2 -H X-Header-2:$test_version -H X-Header-5:$test_7

      # Runs a single command using the runners shell
      - name: Run markdown lint
        run: |
          npm config set fund false 
          npm install remark-cli remark-preset-lint-consistent vfile-reporter-json
          npx remark . --use remark-preset-lint-consistent --report vfile-reporter-json 2> remark-lint-report.json

      - uses: actions/upload-artifact@v3
        with:
          name: remark-lint-report
          path: remark-lint-report.json
              
